In [1]:
import pandas  as pd #Data manipulation
import numpy as np #Data manipulation

In [2]:

df = pd.read_csv('C:/Users/harsh/Dropbox/PC/Downloads/SQLInjectionNLP/SQLInjectionNLP/sqli_new3.csv',encoding='utf-16')

In [3]:
df = df.fillna('')

In [4]:
from nltk.corpus import stopwords

In [44]:
# vectorization of data

from sklearn.feature_extraction.text import CountVectorizer
#vectorizer = CountVectorizer(ngram_range=(2,3), min_df=2, max_df=0.7, max_features=4096, stop_words=stopwords.words('english'))
vectorizer = CountVectorizer(ngram_range=(1,4), max_features=90000, stop_words=stopwords.words('english'))
posts = vectorizer.fit_transform(df['Sentence'].values.astype('U')).toarray()

In [45]:
posts.shape

(3241, 66046)

In [46]:
df.Sentence

0        select * from users where id = 1 or  ( \ )  =...
1        select * from users where id = 1 or  ( \. )  ...
2        select * from users where id = 1 or  ( \+ )  ...
3        select * from users where id = 1 or  ( 1 )  =...
4        select * from users where id = 1 or  ( \+ )  ...
                              ...                        
3236     Thus , developing underlying technical protoc...
3237     For reason , traditional email like open post...
3238     When user &quot; Anna &quot; sends email &quo...
3239           If Gmail account , example , would Google 
3240     This mail server sends content provider Benni...
Name: Sentence, Length: 3241, dtype: object

In [47]:
df.head(100)

Sentence  Label
0    select * from users where id = 1 or  ( \ )  =...      1
1    select * from users where id = 1 or  ( \. )  ...      1
2    select * from users where id = 1 or  ( \+ )  ...      1
3    select * from users where id = 1 or  ( 1 )  =...      1
4    select * from users where id = 1 or  ( \+ )  ...      1
..                                                ...    ...
95   select * from users where id = 1 union select...      1
96   select * from users where id = 1 union select...      1
97   select * from users where id = 1 union select...      1
98   select * from users where id = 1 union select...      1
99   select * from users where id = 1 union select...      1

[100 rows x 2 columns]

In [48]:
df.Label.value_counts()

0    2281
1     960
Name: Label, dtype: int64

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
# split train test data

X_train, X_test, y_train, y_test = train_test_split(df.Sentence, df.Label, test_size=0.2)

In [51]:
X_train.shape

(2592,)

In [52]:
X_test.shape

(649,)

In [53]:
X_train[:4]

2219     The Alb men stood side net undoubtedly experi...
2287     When Santiago sits arched chair , tired life ...
2604                   Children need stability certainty 
595                                          ' or 1 = 1--
Name: Sentence, dtype: object

In [54]:
from sklearn.feature_extraction.text import CountVectorizer

In [55]:
#v=CountVectorizer()
v = CountVectorizer(ngram_range=(2,4))

In [56]:
df.columns

Index(['Sentence', 'Label'], dtype='object')

In [57]:
#df = df.fillna('')

In [58]:
X_train_cv = v.fit_transform(X_train.values)

In [59]:
X_train_cv

<2592x57721 sparse matrix of type '<class 'numpy.int64'>'
	with 66610 stored elements in Compressed Sparse Row format>

In [60]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [61]:
v.get_feature_names_out().shape

(57721,)

In [62]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [63]:
v.vocabulary_

{'the alb': 49887,
 'alb men': 2617,
 'men stood': 30485,
 'stood side': 47979,
 'side net': 45876,
 'net undoubtedly': 32360,
 'undoubtedly experienced': 53655,
 'experienced team': 17583,
 'the alb men': 49888,
 'alb men stood': 2618,
 'men stood side': 30486,
 'stood side net': 47980,
 'side net undoubtedly': 45877,
 'net undoubtedly experienced': 32361,
 'undoubtedly experienced team': 53656,
 'the alb men stood': 49889,
 'alb men stood side': 2619,
 'men stood side net': 30487,
 'stood side net undoubtedly': 47981,
 'side net undoubtedly experienced': 45878,
 'net undoubtedly experienced team': 32362,
 'when santiago': 55950,
 'santiago sits': 43817,
 'sits arched': 46211,
 'arched chair': 5041,
 'chair tired': 9719,
 'tired life': 51875,
 'life genuine': 27824,
 'genuine emotion': 20678,
 'emotion janson': 16386,
 'when santiago sits': 55951,
 'santiago sits arched': 43818,
 'sits arched chair': 46212,
 'arched chair tired': 5042,
 'chair tired life': 9720,
 'tired life genuine':

In [64]:
X_train_np=X_train_cv.toarray()

In [65]:
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [66]:
np.where(X_train_np[0]!=[0])

(array([ 2617,  2618,  2619, 17583, 30485, 30486, 30487, 32360, 32361,
        32362, 45876, 45877, 45878, 47979, 47980, 47981, 49887, 49888,
        49889, 53655, 53656], dtype=int64),)

In [67]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_cv, y_train)



MultinomialNB()

In [68]:
X_test_cv=v.transform(X_test)

In [69]:
from sklearn.metrics import classification_report

In [70]:
y_pred=model.predict(X_test_cv)

In [71]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.88      1.00      0.93       442\n           1       1.00      0.70      0.82       207\n\n    accuracy                           0.90       649\n   macro avg       0.94      0.85      0.88       649\nweighted avg       0.92      0.90      0.90       649\n'

In [72]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.93       442
           1       1.00      0.70      0.82       207

    accuracy                           0.90       649
   macro avg       0.94      0.85      0.88       649
weighted avg       0.92      0.90      0.90       649



In [79]:
Sentence=["select "]
Sentence_count= v.transform(Sentence)
model.predict(Sentence_count)

array([1], dtype=int64)