In [1]:
import pandas  as pd #Data manipulation
import numpy as np #Data manipulation

In [2]:

df = pd.read_csv('C:/Final_Project/SQLInjectionNLP/xss.csv',encoding='utf-16')

In [3]:
df = df.fillna('')

In [4]:
from nltk.corpus import stopwords

In [5]:
# vectorization of data

#from sklearn.feature_extraction.text import CountVectorizer
#vectorizer = CountVectorizer( min_df=2, max_df=0.7, max_features=4096, stop_words=stopwords.words('english'))
#vectorizer = CountVectorizer(ngram_range=(2,4), max_features=4096, stop_words=stopwords.words('english'))
#posts = vectorizer.fit_transform(df['Sentence'].values.astype('U')).toarray()"'

In [6]:
# vectorization of data

from sklearn.feature_extraction.text import CountVectorizer
#vectorizer = CountVectorizer( min_df=2, max_df=0.7, max_features=4096, stop_words=stopwords.words('english'))
vectorizer = CountVectorizer(ngram_range=(1,4), max_features=9096, stop_words=stopwords.words('english'))
posts = vectorizer.fit_transform(df['Sentence'].values.astype('U')).toarray()

In [7]:
posts.shape

(10216, 9096)

In [8]:
df.Sentence

0                                        "-prompt ( 8 ) -"
1                                        '-prompt ( 8 ) -'
2                                   ";a = prompt,a (  ) //
3                                   ';a = prompt,a (  ) //
4             '-eval ( "window['pro'%2B'mpt'] ( 8 ) " ) -'
                               ...                        
10211     A travel industry group welcomed changes , ca...
10212     &quot; We &apos;re pleased FAA recognizes enj...
10213                                                    S
10214                                  Travel Association 
10215                                       modify 9 28845
Name: Sentence, Length: 10216, dtype: object

In [9]:
df.head(100)

Sentence  Label
0                                   "-prompt ( 8 ) -"      1
1                                   '-prompt ( 8 ) -'      1
2                              ";a = prompt,a (  ) //      1
3                              ';a = prompt,a (  ) //      1
4        '-eval ( "window['pro'%2B'mpt'] ( 8 ) " ) -'      1
..                                                ...    ...
95                <html ontouchcancel = alert ( 1 ) >      1
96          <body onorientationchange = alert ( 1 ) >      1
97         "><img src = 1 onerror = alert ( 1 ) >.gif      1
98  <svg xmlns = "http://www.w3.org/2000/svg" onlo...      1
99  GIF89a/*<svg/onload = alert ( 1 ) >*/ = alert ...      1

[100 rows x 2 columns]

In [10]:
df.Label.value_counts()

1    7196
0    3020
Name: Label, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
# split train test data

X_train, X_test, y_train, y_test = train_test_split(df.Sentence, df.Label, test_size=0.2)

In [13]:
X_train.shape

(8172,)

In [14]:
X_test.shape

(2044,)

In [15]:
X_train[:4]

4708    <style>:target {transform: rotate ( 180deg ) ;...
5642    <td onkeypress = "alert ( 1 ) " contenteditabl...
8741     British police serve Assange extradition noti...
7087    <DIV STYLE = "background-image: url ( javascri...
Name: Sentence, dtype: object

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
v=CountVectorizer(ngram_range=(1,4))


In [19]:
df.columns

Index(['Sentence', 'Label'], dtype='object')

In [20]:
#df = df.fillna('')

In [21]:
X_train_cv = v.fit_transform(X_train.values)

In [22]:
X_train_cv

<8172x116563 sparse matrix of type '<class 'numpy.int64'>'
	with 246455 stored elements in Compressed Sparse Row format>

In [23]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
v.get_feature_names_out().shape

(116563,)

In [25]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [26]:
v.vocabulary_

{'style': 96725,
 'target': 101224,
 'transform': 107255,
 'rotate': 86828,
 '180deg': 1624,
 'id': 48643,
 'transition': 107293,
 '2s': 3268,
 'ontransitionrun': 72715,
 'alert': 7830,
 'style target': 97649,
 'target transform': 101255,
 'transform rotate': 107271,
 'rotate 180deg': 86829,
 '180deg style': 1625,
 'style id': 97091,
 'id style': 49336,
 'style transition': 97709,
 'transition transform': 107317,
 'transform 2s': 107259,
 '2s ontransitionrun': 3269,
 'ontransitionrun alert': 72716,
 'style target transform': 97652,
 'target transform rotate': 101256,
 'transform rotate 180deg': 107272,
 'rotate 180deg style': 86830,
 '180deg style id': 1716,
 'style id style': 97092,
 'id style transition': 49343,
 'style transition transform': 97713,
 'transition transform 2s': 107320,
 'transform 2s ontransitionrun': 107260,
 '2s ontransitionrun alert': 3270,
 'style target transform rotate': 97653,
 'target transform rotate 180deg': 101257,
 'transform rotate 180deg style': 107273,


In [27]:
X_train_np=X_train_cv.toarray()

In [28]:
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
np.where(X_train_np[0]!=[0])

(array([  1624,   1625,   1716,   1717,   3268,   3269,   3270,   7830,
         48643,  49336,  49343,  49345,  72715,  72716,  86828,  86829,
         86830,  86876,  96725,  97091,  97092,  97094,  97649,  97652,
         97653,  97709,  97713,  97715, 101224, 101255, 101256, 101257,
        107255, 107259, 107260, 107261, 107271, 107272, 107273, 107293,
        107317, 107320, 107321], dtype=int64),)

In [30]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_cv, y_train)



MultinomialNB()

In [31]:
X_test_cv=v.transform(X_test)

In [32]:
from sklearn.metrics import classification_report

In [33]:
y_pred=model.predict(X_test_cv)

In [34]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      0.96      0.98       617\n           1       0.98      1.00      0.99      1427\n\n    accuracy                           0.99      2044\n   macro avg       0.99      0.98      0.99      2044\nweighted avg       0.99      0.99      0.99      2044\n'

In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98       617
           1       0.98      1.00      0.99      1427

    accuracy                           0.99      2044
   macro avg       0.99      0.98      0.99      2044
weighted avg       0.99      0.99      0.99      2044



In [41]:
Sentence=["selecting items"]
Sentence_count= v.transform(Sentence)
model.predict(Sentence_count)

array([0], dtype=int64)